version: '3.8'

services:
  # API Service
  aml-api:
    build: .
    container_name: aml-api
    ports:
      - "8000:8000"
    environment:
      - GNN_FRAMEWORK=pyg
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    command: ["python", "api/main.py"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - aml-network

  # Dashboard Service
  aml-dashboard:
    build: .
    container_name: aml-dashboard
    ports:
      - "8501:8501"
    environment:
      - GNN_FRAMEWORK=pyg
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    command: ["streamlit", "run", "dashboard/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    depends_on:
      aml-api:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - aml-network

networks:
  aml-network:
    driver: bridge 